import classNames from "classnames";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import TerrainCanvas from "../three/terrain/TerrainCanvas";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={classNames(styles["terrain-section"], "pb-5")}>
          <div className="container">
            <div className="pb-5">
              <div className="position-relative">
                <div className="row pb-md-6 pb-lg-4">
                  <div className="col-12 col-md-10">
                    <div className={styles["terrain-canvas-parent"]}>
                      <TerrainCanvas
                        style={{
                          position: "absolute",
                          width: "100%",
                          height: "100%",
                        }}
                      />
                    </div>
                  </div>
                </div>

                <div className="row position-md-absolute bottom-md-0 right-md-0 pointer-events-md-none">
                  <div className="col-md-7"></div>
                  <div className="col-12 col-md-5">
                    <p className="text-center text-md-right font-size-4 font-weight-light">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Nullam feugiat efficitur vulputate. Vestibulum ac leo
                      turpis. Cras lobortis ipsum ut lacinia porttitor. In eu
                      condimentum est. Phasellus venenatis nec augue eget
                      gravida.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <p>Lorem Ipsum</p>
          </div>
        </section>

        <section className={classNames(styles["blue-background"], "pb-5")}>
          <div className="container">
            <div className="row">
              <div className="col-6">
                <h1>Lorem Ipsum</h1>
                <h2>Lorem Ipsum</h2>
                <h3>Lorem Ipsum</h3>
                <h4>Lorem Ipsum</h4>
                <h5>Lorem Ipsum</h5>
                <h6>Lorem Ipsum</h6>

                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Aenean elementum bibendum sem sed pretium. Ut nisl lorem,
                  fermentum eget felis in, malesuada scelerisque dolor. Sed
                  tincidunt justo ut nulla faucibus, ut interdum nisi ornare.
                  Sed at mi vitae lorem tincidunt interdum. Phasellus non
                  lacinia magna. Nulla viverra aliquam leo, et laoreet mi
                  hendrerit quis. Maecenas tincidunt velit nec maximus semper.
                  Aliquam sit amet feugiat magna. Integer tempor sapien sagittis
                  nunc sodales, sit amet iaculis nisi posuere. Pellentesque
                  tincidunt ut massa sed scelerisque.
                </p>

                <p>
                  Proin orci odio, dapibus a tristique nec, consectetur eu
                  risus. Nunc vitae elit fermentum dui volutpat dapibus. Morbi
                  semper congue placerat. Donec sit amet leo lacus. Maecenas in
                  est eu urna molestie aliquet. Integer id dignissim purus. Sed
                  finibus lectus ligula, a commodo mauris molestie sed. Quisque
                  eu tristique dolor. Aliquam sit amet facilisis nisi, vitae
                  convallis nunc. Pellentesque pellentesque risus ullamcorper
                  enim hendrerit iaculis. Nullam tempor bibendum sem ac
                  eleifend. Mauris imperdiet aliquam mauris, vel fermentum
                  mauris sollicitudin iaculis. Sed sodales a tellus id egestas.
                  Quisque sit amet egestas arcu, nec tincidunt nibh. Fusce eu
                  tellus nec arcu ultricies laoreet. Fusce accumsan condimentum
                  velit, sed hendrerit justo dapibus sed.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
